language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
